version: '3'

services:
  run-tests:
    build:
      context: .
      dockerfile: Dockerfile
    command: pytest

  run-method:
    build:
      context: .
      dockerfile: Dockerfile
    command: python run_method.py
