FROM jupyter/minimal-notebook
# Install essential Python packages
RUN python3 -m pip --no-cache-dir install \
   pandas \
   seaborn \
   numpy \
   scipy \
   scikit-learn \
   matplotlib \
   geopandas \
   statsmodels